import './globals.css'
import { Raleway } from 'next/font/google'
import Nav from '@/components/nav'

const raleway = Raleway({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={raleway.className}>
        <Nav/>
        {children}
        </body>
    </html>
  )
}
